### ISSUE TITLE
Model execution fails with output_raw_values missing from RaidionicsLogic

### ISSUE THREAD

**Issue by errollgarner** [dbouget/Raidionics-Slicer#1]
I tried running the meningioma segmentation model, but when clicking on Run the segmentation, the method never finishes and the following error shows in the python console:
Traceback (most recent call last):
  File "C:/git/Raidionics-Slicer/Raidionics/Raidionics\src\gui\Segmentation\BaseSegmentationWidget.py", line 55, in on_interactive_slider_moved
    self.model_execution_widget.on_interactive_slider_moved(value, self.model_interface_widget.model_parameters)
  File "C:/git/Raidionics-Slicer/Raidionics/Raidionics\src\gui\Segmentation\ModelsExecutionWidget.py", line 194, in on_interactive_slider_moved
    original_data = deepcopy(RaidionicsLogic.getInstance().output_raw_values[current_class])
AttributeError: 'RaidionicsLogic' object has no attribute 'output_raw_values'

**Comment by dbouget** [comment]
Can you show me the content of the _Logging_ tab, located to the right of the _Segmentation_ and _Reporting (RADS)_ tabs?

![image](https://user-images.githubusercontent.com/24223628/167365702-4afeccd5-1a1e-4a6b-a8a5-b4c3b0a421d8.png)

**Comment by errollgarner** [comment]
Thank you! It looks like whatever the problem was initially, it was fixed with the latest docker image update.

I tried rerunning the segmentation to reproduce the error, but couldn't reproduce it. When selecting the meningioma model, I was first prompted to update the docker image. After doing so, the segmentation worked without issue.
